version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:80"
    networks:
      - monitoring
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  prometheus:
    image: prom/prometheus:v2.47.2 
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD="abc123"
      - GF_SECURITY_ADMIN_USER="admin"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring: